### ISSUE TITLE
Compatibility with safeVisionary2

### ISSUE THREAD

**Issue by michmaz061** [SICKAG/sick_visionary_python_base#1]
Can the presented solution also be used with safeVisionary2 device, which also has CoLa-2 protocol, for extracting data from it without using a UDP communication?

**Comment by peichtoSICKAG** [comment]
The CoLa-2 protocol is used only for parameterization. The data streaming differs between the safe and non-safe devices. Thus, while it should be possible to reuse the CoLa-2 protocol layer to interact with the safeVisionary2 device you will find no support here for the different streaming protocol.
