### ISSUE TITLE
Request for Python Sample Codes for Visionary-T mini CX

### ISSUE THREAD

**Issue by jethro-huang-hub** [SICKAG/sick_visionary_python_base#2]
## Summary

Request for Python Sample Codes for Visionary-T mini CX

## Motivation
Dear R&D Team,

We have a customer who hopes to use the Python SDK under the Visionary-T mini CX with firmware version 2.1.0, and conduct a quick test through some sample codes. 

However, only the SDK encapsulation files were found in the code repository. 

Could you provide some sample codes such as point cloud generation and saving?

Thank you!

**Comment by zimmefaSICKAG** [comment]
Please use https://github.com/SICKAG/sick_visionary_samples as a starting point. There we have several samples - e.g. how to create and store a pointcloud - which are well documented. All samples are available in C++ and Python.
